{
 "title": "Longhorn",
 "description": "Longhorn Metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Longhorn Public Metrics Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "The metrics we're showing here are collected using Longhorn Upgrade Responder Service, which will notify the user when a new release of Longhorn is available.\n\nThe source code is available at https://github.com/longhorn/upgrade-responder ."
   },
   "content": "The metrics we're showing here are collected using Longhorn Upgrade Responder Service, which will notify the user when a new release of Longhorn is available.\n\nThe source code is available at https://github.com/longhorn/upgrade-responder .",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Node Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "byTime_1h",
     "query": "SELECT last(\"total\") FROM \"upgrade_request_down_sampling\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growth Rate per Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data_1 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n\ndata_2 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: 2017-01-01T00:00:00Z, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> timeShift(duration: 1mo)\n\n  \njoin(tables: {d1: data_1, d2: data_2}, on: [\"_time\"], method: \"inner\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: ((float(v: r._value_d1) - float(v: r._value_d2)) / float(v: r._value_d2)) * 100.0\n    }))\n  |> filter(fn: (r) => r._value > -20.0 and r._value < 50.0 )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Node Longhorn Versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_app_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "longhorn_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "byLonghornVersion_1h",
     "query": "SELECT last(\"total\") FROM \"by_app_version_down_sampling\" WHERE $timeFilter GROUP BY time($__interval), \"app_version\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Nodes Kubernetes Version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_kubernetes_version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "kubernetes_version" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "byK8sVersion_1h",
     "query": "SELECT last(\"total\") FROM \"by_kubernetes_version_down_sampling\" WHERE $timeFilter GROUP BY time($__interval), \"kubernetes_version\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}