{
 "title": "Longhorn Growth Rate",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Active Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total\") FROM \"upgrade_request_down_sampling\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growth Rate per Month",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data_1 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n\ndata_2 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: 2017-01-01T00:00:00Z, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> timeShift(duration: 1mo)\n\n  \njoin(tables: {d1: data_1, d2: data_2}, on: [\"_time\"], method: \"inner\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: ((float(v: r._value_d1) - float(v: r._value_d2)) / float(v: r._value_d2)) * 100.0\n    }))\n  |> filter(fn: (r) => r._value > -20.0 and r._value < 50.0 )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growth Rate per Quarter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data_1 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n\ndata_2 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: 2017-01-01T00:00:00Z, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> timeShift(duration: 3mo)\n\n  \njoin(tables: {d1: data_1, d2: data_2}, on: [\"_time\"], method: \"inner\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: ((float(v: r._value_d1) - float(v: r._value_d2)) / float(v: r._value_d2)) * 100.0\n    }))\n  |> filter(fn: (r) => r._value > -20.0 and r._value < 100.0 )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Growth Rate per Year",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "data_1 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n\ndata_2 = from(bucket: \"longhorn_upgrade_responder/autogen\")\n  |> range(start: 2017-01-01T00:00:00Z, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"upgrade_request_down_sampling\" and\n    r._field == \"total\"\n  )\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: false)\n  |> timeShift(duration: 1y)\n\n  \njoin(tables: {d1: data_1, d2: data_2}, on: [\"_time\"], method: \"inner\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _value: ((float(v: r._value_d1) - float(v: r._value_d2)) / float(v: r._value_d2)) * 100.0\n    }))\n  |> filter(fn: (r) => r._value > -100.0 and r._value < 600.0 )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}